// @ts-check
/**
 * Community sidebar — autogenerated from website/community.
 * index.md and events.md are authored; the rest are generated from repo-root
 * files (CONTRIBUTING.md, …) by the sync tool (`./bin/llmd-site sync`).
 * Order follows sidebar_position.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  communitySidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
