// @ts-check
/**
 * Guides sidebar — autogenerated from website/guides.
 * index.md is authored; the rest are generated from repo-root
 * guides/<name>/README.md files (llm-d/llm-d) by the sync tool
 * (`./bin/llmd-site sync`). Order follows sidebar_position.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  guidesSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
