// @ts-check
/**
 * Dev docs sidebar — autogenerated from website/docs with metadata from menu-config.json.
 * Labels, ordering, and collapse state are applied by sidebarItemsGenerator
 * (see scripts/lib/sidebar.mjs). Adding a doc is zero-config: it appears on the next build.
 *
 * Released versions use their own frozen versioned_sidebars/*.json instead.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
