import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the mirrored docs/ tree: folder structure +
// _category_.json (labels/position/collapse) + page frontmatter (sidebar_position,
// sidebar_label). All of it lives in llm-d/llm-d/docs — edit there, not here.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
